version: '3.3'

services:  
  postgres:
    container_name: postgres_container
    image: postgres:14.1        
    environment:      
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_TEST_DB: ${POSTGRES_TEST_DATABASE}
      PGDATA: /data/postgres    
    volumes:
       - ./postgres:/data/postgres     
       - ./src/database/scripts:/docker-entrypoint-initdb.d/
     
     
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    depends_on:
      -   postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/data/postgres/lib/pgadmin

    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  nestjs-network:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: