version: '3.3'

services:  
  postgres:
    container_name: postgres_container
    image: postgres:14.1        
    environment:      
      DATABASE_USER: ${TYPEORM_USER}
      DATABASE_PASSWORD: ${TYPEORM_PASSWORD}
      DATABASE_NAME: ${TYPEORM_NAME}
      DATABASE_TEST_NAME: ${TYPEORM_TEST_NAME}
      PGDATA: /data/postgres    
    volumes:
       - ./postgres:/data/postgres     
       - ./src/database/scripts:/docker-entrypoint-initdb.d/
     
     
    ports:
      - "${TYPEORM_PORT}:${TYPEORM_PORT}"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    depends_on:
      -   postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/data/postgres/lib/pgadmin

    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  nestjs-network:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: